# VMT per household, per day
# a useful table when analyzing how geographic or household-level attributes
# (e.g., income, number of kids) affect how much driving is done to support an entire household.


# find VMT per household, just the driving done by household members:
hh_vmt <-
  tbi$trip %>%
  filter(vehicle_driver == "Driver") %>%
  filter(grepl("vehicle|car", x = mode_type_detailed)) %>%
  group_by(hh_id, day_num) %>%
  summarize(hh_vmt = sum(distance)) %>%
  ungroup()


# Households with multiple days of survey need to be aggregated across
# multiple survey dates. To do this, we'll use day weights, and attribute any VMT
# generated by the household to the "head of household" -- the person with the LOWEST person_id (hh_id_1).
# find heads of household's days:
head_of_hh_days <-
  tbi$day %>%
  # only want weekdays
  filter(day_weight > 0) %>%
  # this finds head of household:
  group_by(hh_id, day_num) %>%
  arrange(person_id) %>%
  slice_head(n = 1) %>%
  select(hh_id, person_id, day_num, day_weight) %>%
  ungroup() %>%
  rename(head_of_hh_per_id = person_id)

hh_vmt_perday <-
  head_of_hh_days %>%
  left_join(hh_vmt) %>%
  replace_na(list(hh_vmt = 0))


rm(hh_vmt, head_of_hh_days)
