# Households with multiple days of survey need to be aggregated across
# multiple survey dates. To do this, we'll use day weights, and attribute any VMT
# generated by the household to the "head of household" -- the person with the LOWEST person_id (hh_id_1).
# find heads of household's days:
head_of_hh_days <-
  tbi_tables$day %>%
  # only want weekdays
  filter(day_weight > 0) %>%
  # this finds head of household:
  group_by(hh_id, day_num) %>%
  arrange(person_id) %>%
  slice_head(n = 1) %>%
  select(hh_id, person_id, day_num, day_weight) %>%
  ungroup() %>%
  rename(head_of_hh_per_id = person_id)

vmt_per_veh <-
  tbi_tables$trip %>%
  filter(vehicle_driver == "Driver") %>%
  filter(grepl("vehicle|car", x = mode_type_detailed)) %>%
  group_by(hh_id, veh_id, day_num) %>%
  summarize(veh_vmt = sum(distance)) %>%
  ungroup()

tbi_tables$vmt_per_veh <-
  # all the heads of household:
  head_of_hh_days %>%
  # joined to all the cars available to them:
  left_join(tbi_tables$veh %>%
    select(hh_id, veh_id)) %>%
  # only for people with cars:
  filter(!is.na(veh_id)) %>%
  # all the miles they were driven:
  left_join(vmt_per_veh) %>%
  # zero miles for cars not driven
  replace_na(list(veh_vmt = 0))


rm(head_of_hh_days, vmt_per_veh, head_of_hh_days)
